# Generated by Django 4.1.3 on 2022-11-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contact_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
    ]
