# Generated by Django 4.1.3 on 2022-11-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_contact_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
    ]
